### ISSUE TITLE
Amplitude-modulation distortion in PV_PlayBuf / PV_RecordBuf in Linux

### ISSUE THREAD

**Issue by jamshark70** [supercollider/sc3-plugins#8]
This has been an issue for at least a couple of years. I'm logging it now because Tim fixed an issue related to windowing functions in Linux, which I thought might have been related to this problem. It isn't -- I tested against SC's current master, and the PV_PlayBuf / PV_RecordBuf persists.

I'll assign myself temporarily because I want to see if Tim's FFT fix for SC might help these plugins. He replaced some uses of memcpy with memmove. I haven't looked at Josh's code in detail, but it seems entirely possible that memcpy could be in there and _maybe_ it would help to update that. Can't try it just this second. Maybe later today.

If that fails, then I'll reassign to Josh.

**Comment by jamshark70** [comment]
FWIW, necrobump, but `PV_RecordBuf` now crashes the server in Linux:

```
b = Buffer(s, 44100*2, 2);
c = Buffer(s, b.duration.calcPVRecSize(512, 0.5, 44100), 1);

(
a = {
	var sig = SinOsc.ar(XLine.kr(200, 600, b.duration, doneAction: 2)),
	fft = FFT(LocalBuf(512), sig),
	fft2 = PV_Copy(fft, LocalBuf(512));

	// comment out this line, no crash
	fft2 = PV_RecordBuf(fft, c, loop: 0);

	RecordBuf.ar([IFFT(fft), DC.ar(0)], b, loop: 0);
	Silent.ar(1)
}.play;
)
```

**Comment by jamshark70** [comment]
```
Thread 9 "scsynth" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7ea2700 (LWP 18105)]
0x00007fffbaae4582 in PV_RecordBuf_next (unit=0x7fffa58669dc, 
    inNumSamples=<optimized out>)
    at /home/path/to/sc3-plugs-hjh/source/JoshUGens/JoshPVUGens.cpp:1691
1691		    databufData[0] = buf->samples;

(gdb) where
#0  0x00007fffbaae4582 in PV_RecordBuf_next(PV_RecordBuf*, int) (unit=0x7fffa58669dc, inNumSamples=<optimized out>)
    at /home/path/to/sc3-plugs-hjh/source/JoshUGens/JoshPVUGens.cpp:1691
#1  0x00005555555ab8cc in Graph_Calc_unit(Unit*) (unit=<optimized out>)
    at /home/path/to/supercollider/server/scsynth/SC_Graph.cpp:471
#2  0x00005555555ab8cc in Graph_Calc(Graph*) (inGraph=<optimized out>)
    at /home/path/to/supercollider/server/scsynth/SC_Graph.cpp:489
#3  0x00005555555b348a in Group_Calc(Group*) (inGroup=<optimized out>)
    at /home/path/to/supercollider/server/scsynth/SC_Group.cpp:72
#4  0x00005555555b348a in Group_Calc(Group*) (inGroup=<optimized out>)
    at /home/path/to/supercollider/server/scsynth/SC_Group.cpp:72
#5  0x00005555555aaffa in SC_JackDriver::Run() (this=0x7fffa4a4c010)
    at /home/path/to/supercollider/server/scsynth/SC_Jack.cpp:529
#6  0x00005555555ab34c in sc_jack_process_cb(jack_nframes_t, void*) (numFrames=<optimized out>, arg=<optimized out>)
    at /home/path/to/supercollider/server/scsynth/SC_Jack.cpp:187
#7  0x00007ffff6ee2f95 in  () at /usr/lib/x86_64-linux-gnu/libjack.so.0
#8  0x00007ffff6ee2738 in  () at /usr/lib/x86_64-linux-gnu/libjack.so.0
#9  0x00007ffff6efa626 in  () at /usr/lib/x86_64-linux-gnu/libjack.so.0
#10 0x00007ffff79b86db in start_thread (arg=0x7ffff7ea2700)
    at pthread_create.c:463
#11 0x00007ffff5cac88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by joshpar** [comment]
I can fix that! 

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by jamshark70** [comment]
I tried again; I can no longer reproduce the broken sound.

Closing.
